# Generated by Django 3.2.2 on 2021-05-29 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycinema', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opinions',
            name='cinema',
        ),
        migrations.RemoveField(
            model_name='opinions',
            name='film',
        ),
        migrations.RemoveField(
            model_name='opinions',
            name='staff',
        ),
    ]
