# Generated by Django 3.2.3 on 2021-05-21 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycinema', '0002_auto_20210522_0057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='name',
            new_name='title',
        ),
    ]
