# Generated by Django 3.2.2 on 2021-06-04 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycinema', '0003_rename_filmopinion_filmopinions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmopinions',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filmopinions', to='mycinema.cinema'),
        ),
    ]
