# Generated by Django 3.2.2 on 2021-06-04 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycinema', '0004_alter_filmopinions_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filmopinions',
            old_name='post',
            new_name='filmpost',
        ),
    ]
