# Generated by Django 3.2.2 on 2021-06-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycinema', '0005_rename_post_filmopinions_filmpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='total_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='film',
            name='total_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='news',
            name='total_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='staff',
            name='total_rating',
            field=models.FloatField(default=0),
        ),
    ]
