# Generated by Django 3.2.2 on 2021-05-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycinema', '0007_auto_20210523_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('MOVIE', 'MOVIE'), ('TVSERIES', 'TVSERIES'), ('DIRECTORS', 'DIRECTORIES'), ('CINEMAS', 'CINEMAS'), ('ACTORS', 'ACTORS'), ('OTHERS', 'OTHERS')], max_length=50, null=True),
        ),
    ]
