# Generated by Django 3.2.2 on 2021-06-04 22:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mycinema', '0007_film_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.CharField(default='', max_length=100)),
                ('main_description', models.TextField(blank=True)),
                ('total_rating', models.FloatField(default=0)),
                ('is_accepted', models.BooleanField(default=False)),
                ('moderator', models.CharField(default='-', max_length=50)),
                ('opinion_counter', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Comedy', 'Comedy'), ('Crime', 'Crime'), ('Fantasy', 'Fantasy'), ('Historical', 'Historical'), ('Horror', 'Horror'), ('Musical', 'Musical'), ('Romance', 'Romance'), ('Science Fiction', 'Science Fiction'), ('Thriller', 'Thriller'), ('Western', 'Western')], max_length=50, null=True)),
                ('image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='series/film_default.png', force_format=None, keep_meta=True, quality=90, size=[256, 256], upload_to='series/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
