# Generated by Django 3.2.2 on 2021-06-04 22:45

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('mycinema', '0008_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='staff/staff_default.png', force_format=None, keep_meta=True, quality=90, size=[256, 256], upload_to='cinema/'),
        ),
        migrations.AlterField(
            model_name='series',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='series/series_default.png', force_format=None, keep_meta=True, quality=90, size=[256, 256], upload_to='series/'),
        ),
    ]
