# Generated by Django 3.2.2 on 2021-05-24 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mycinema', '0011_opinions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinemas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('total_rating', models.IntegerField()),
                ('is_accepted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Comedy', 'Comedy'), ('Crime', 'Crime'), ('Fantasy', 'Fantasy'), ('Historical', 'Historical'), ('Horror', 'Horror'), ('Musical', 'Musical'), ('Romance', 'Romance'), ('Science Fiction', 'Science Fiction'), ('Thriller', 'Thriller'), ('Western', 'Western')], max_length=50, null=True)),
                ('short_description', models.CharField(max_length=100)),
                ('main_description', models.TextField(blank=True)),
                ('total_rating', models.IntegerField()),
                ('is_accepted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='opinions',
            name='cinemas_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='opinions',
            name='films_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='opinions',
            name='news_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='opinions',
            name='staff_id',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profession', models.CharField(choices=[('Actor', 'Actor'), ('Director', 'Director'), ('Producer', 'Producer'), ('Director of Photography', 'Director of Photography'), ('Costume Designer', 'Costume Designer'), ('Movie Editor', 'Movie Editor'), ('Composer', 'Composer')], max_length=50, null=True)),
                ('short_description', models.CharField(max_length=100)),
                ('main_description', models.TextField(blank=True)),
                ('total_rating', models.IntegerField()),
                ('is_accepted', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
