# Generated by Django 3.2.2 on 2021-05-27 22:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mycinema', '0012_auto_20210524_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('total_rating', models.IntegerField()),
                ('is_accepted', models.BooleanField(default=False)),
                ('author', models.CharField(max_length=100)),
                ('authors', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Comedy', 'Comedy'), ('Crime', 'Crime'), ('Fantasy', 'Fantasy'), ('Historical', 'Historical'), ('Horror', 'Horror'), ('Musical', 'Musical'), ('Romance', 'Romance'), ('Science Fiction', 'Science Fiction'), ('Thriller', 'Thriller'), ('Western', 'Western')], max_length=50, null=True)),
                ('short_description', models.CharField(max_length=100)),
                ('main_description', models.TextField(blank=True)),
                ('total_rating', models.IntegerField()),
                ('is_accepted', models.BooleanField(default=False)),
                ('author', models.CharField(max_length=100)),
                ('authors', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Cinemas',
        ),
        migrations.DeleteModel(
            name='Films',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='moderator',
        ),
        migrations.AddField(
            model_name='staff',
            name='authors',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staff',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='cinema',
            name='repertoire',
            field=models.ManyToManyField(to='mycinema.Film'),
        ),
        migrations.AddField(
            model_name='staff',
            name='related_films',
            field=models.ManyToManyField(to='mycinema.Film'),
        ),
    ]
