# Generated by Django 3.2.2 on 2021-05-28 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mycinema', '0013_auto_20210528_0059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cinema',
            old_name='description',
            new_name='main_description',
        ),
        migrations.RenameField(
            model_name='opinions',
            old_name='cinemas_id',
            new_name='cinema_id',
        ),
        migrations.RenameField(
            model_name='opinions',
            old_name='films_id',
            new_name='film_id',
        ),
        migrations.RemoveField(
            model_name='cinema',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='film',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='authors',
        ),
        migrations.AddField(
            model_name='cinema',
            name='moderator',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='cinema',
            name='opinion_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cinema',
            name='short_description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='film',
            name='moderator',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='film',
            name='opinion_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='news',
            name='moderator',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='news',
            name='opinion_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='total_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='staff',
            name='moderator',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='staff',
            name='opinion_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='total_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='film',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='film',
            name='short_description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='film',
            name='total_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staff',
            name='short_description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='total_rating',
            field=models.IntegerField(default=0),
        ),
    ]
