# Generated by Django 3.2.2 on 2021-05-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycinema', '0014_auto_20210528_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='moderator',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='film',
            name='moderator',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='news',
            name='moderator',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='staff',
            name='moderator',
            field=models.CharField(default='', max_length=50),
        ),
    ]
